### ISSUE TITLE
vehicle_id field can be longer than 10 characters

### ISSUE THREAD

**Issue by rv3392** [CUTR-at-USF/gtfsrdb#14]
Not 100% sure if this library is still being maintained, but I have an issue where my local transport agency uses vehicle_id's that are 13 characters long (longer than the expected 10 characters) which causes the tool to crash. 

I've got a fix using String(64) instead of String(10) for the vehicle_id column in my own fork which seems to fix it. I'd be happy to open a PR with this change if it seems like something that doesn't go against the GTFS spec.

**Comment by barbeau** [comment]
@rv3392 We're not actively using it, but a PR for this would be welcome!
