### ISSUE TITLE
Example link obsolete

### ISSUE THREAD

**Issue by XavierPrudent** [CUTR-at-USF/gtfsrdb#2]
Dear authors,
Thank you for sharing your work.
The Bay Area example you provided uses a link dead by now, I suggest you replace it by
http://api.bart.gov/gtfsrt/tripupdate.aspx

kind regards,
Xavier Prudent

**Comment by barbeau** [comment]
Thanks @XavierPrudent!  I fixed this in https://github.com/CUTR-at-USF/gtfsrdb/commit/9ecb31dafe6fff95cceef7002b44500416dd741f (I accidentally referenced the wrong issue number in the commit).
